# Generated by Django 6.0.6 on 2026-06-13 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='driveroffer',
            name='status',
            field=models.CharField(default='pending', max_length=20),
        ),
    ]
